### ISSUE TITLE
Detected as MATPLOTLIB._TRI.PYD, W32.Worm.Butterfly by Webroot

### ISSUE THREAD

**Issue by AlexHeylin** [ccampo133/Plot-Pings-in-Python#6]
I've not determined if this is false positive or real detection - simply reporting it.

**Comment by ccampo133** [comment]
Must be something with your local matplotlib. The code here uses matplotlib properly and is not malicious.

**Comment by AlexHeylin** [comment]
I just used your Windows binary. I don't have matplotlib installed locally, apart from the one in this project binary. Thanks
